🐛 fix: next.config.js 12버전에 맞는 설정으로 변경
depromeet/toks-web pull request #46
Opened 2022-11-14 08:50 UTC by dengoyoon

## 💡 왜 PR을 올렸나요?
- next.config.js의 설정이 13버전으로 남아있어서 quiz서비스의 next.config.js의 설정과 같이 12버전으로 동기화했습니다
- 빌드 후 실행에 문제없는지 체크하였습니다

## 💁 무엇이 어떻게 바뀌나요?
- 디자인 레퍼런스: 
- 관련 슬랙 링크: 

## 💬 리뷰어분들께

2022-11-16 00:31 UTC, minsgy requested changes
PR 컨벤션 맞춰주실 수 있나요~?

2022-11-16 07:12 UTC, dengoyoon commented
아 혹시 타이틀 때문에 그런가요?
**[#46] next.config.js 12버전에 맞는 설정으로 변경**
이렇게 변경하면 될까요??

2022-11-16 07:23 UTC, LineGu commented
이건 괜찮을거 같네요.
`feat(변경된 서비스 or package): 제목`

이렇게 하시면 됩니다.

2022-11-16 07:23 UTC, LineGu approved these changes

2022-11-16 07:26 UTC, dengoyoon commented
옹 네넵 감사합니다! 변경했어요!

2022-11-16 08:05 UTC, dengoyoon commented
엇 이거 혹시 승인 해주신거 같은데 머지도 시켜주실 수 있나요?!

2022-11-16 08:37 UTC, dengoyoon commented
아하 넵넵 감사합니다~~

2022-11-17 07:23 UTC, dengoyoon commented
@minsgy 민석님 혹시 시간 여유 있으실때 approve 한번 해주실수 있을까요? 코멘트 남겨주신 분들 모두 approve가 필요하다고 해서요!

2022-11-17 07:37 UTC, minsgy approved these changes
👍 👍 👍

2022-11-17 07:37 UTC, merged